apiVersion : apps/v1
kind: Deployment
metadata:
  name: imafidondevopsjourneyusingazuredevops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imafidondevopsjourneyusingazuredevops
  template:
    metadata:
      labels:
        app: imafidondevopsjourneyusingazuredevops 
    spec:
      containers:
        - name: imafidondevopsjourneyusingazuredevops 
          image: dadregistry.azurecr.io/imafidondevopsjourneyusingazuredevops
          ports:
          - containerPort: 80